### PR TITLE
H20EZE 02.10 is partial better to 02.13, keep both

### PR DESCRIPTION
**Pull request by informer2016**
If we look at Release_Note.txt inside the archive, we could see all the differences between 02.10 and 02.13.
Although 02.13 adds Tiano decompress support and a few extra features / tweaks, version 02.10 is partially better:
1) 02.10 has "SetupEditor" in File menu, while it has been removed since 02.11 so 02.13 doesn't have it
2) 02.10 shows descriptions for more BIOS modules in "Components --> Modules --> Module Export" menu
e.g. I open one particular BIOS in 02.10 and see that it has a lot of text descriptions:
...
0325B5A1-0937-4A4F-B8AF-EC3F80EE6B35 (SataController)
...
07A9330A-F347-11D4-9A49-0090273FC14D (LegacyMetronome)
...
0997E770-756E-4139-BF3F-7FC2A308177E (SmmS3)
...
and so on. Meanwhile, from the examples above, 02.13 has text description only for 0997E770-756E-4139-BF3F-7FC2A308177E - it is SmmS3
Descriptions are very valuable for understanding the BIOS functions, and so far 02.13 loses to 02.10 in this relation

### CODE REVIEW

**Comment by informer2016** [comment]
@walkman8196 I believe that both 02.10 and 02.13 version have a right to exist in the same repository, because - as described above - each version has its' own advantages and 02.10 is partially better than 02.13 in some relations... Thank you very much for sharing 02.13 version, dear Friend ! Please share more versions if you have, even the older ones, - it will be interesting to try them in action ;)

**Comment by walkman8196** [comment]
Hey. I'm glad to hear that someone is also interested in this topic editing bios insyde h2o. And thanks for the comparison, I will keep in mind.
I also have H2OUVE_100.0.9.2.
Your version of H2OUVE_100.0.16.8 does not work for me.

**Comment by walkman8196** [comment]
[H2OUVE_100.0.9.2.zip](https://github.com/walkman8196/Insider_BIOS_Tools/files/1102620/H2OUVE_100.0.9.2.zip)

**Comment by informer2016** [comment]
@walkman8196 Initially I wanted to post issue about it, but the issues were closed and I could reach you only with a pull request :nerd_face: Thank you very much for this share! I also promise to share more tools with you if I find them. Sharing is caring :wink:

**Comment by walkman8196** [comment]
Thank you, I will also share

**Comment by s-sosnitskiy80** [comment]
@walkman8196 Thank you very much for your contributions! Also thanks to @informer2016 for the feedback. I got permission to add a few more outdated tools that are already available online, so I have added H20EZE_x86_WIN_100.00.02.13 , H20FFT_x86_WIN_5.74 and H20UVE_100.00.9.2 to our official repository which is available here - https://github.com/s-sosnitskiy80/Insider_BIOS_Tools . Good luck!

**Comment by s-sosnitskiy80** [comment]
@walkman8196 Thank you very much for your contributions! Also thanks to @informer2016 for the feedback. I got permission to add a few more outdated tools that are already available online, so I have added H20EZE_x86_WIN_100.00.02.13 , H20FFT_x86_WIN_5.74 and H20UVE_100.00.9.2 to our official repository which is available here https://github.com/s-sosnitskiy80/Insider_BIOS_Tools Good luck!

**Pull request merged**
